name: nuxt-portfolio

services:
  backend:
    build: ./services/backend
    ports:
      - 5050:5050
    restart: always

  frontend:
    build: ./services/frontend
    ports:
      - 8080:8080
    restart: always