name: nuxt-portfolio

services:
  frontend:
    build: ./
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    restart: always

volumes:
  node_modules: